# Generated by Django 3.2.13 on 2022-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCarnaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=40)),
                ('hora', models.CharField(max_length=5)),
                ('local', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesDoSiteDeCarnaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo01', models.CharField(max_length=45)),
                ('titulo02', models.CharField(max_length=45)),
                ('texto02', models.TextField()),
            ],
        ),
    ]
