# Generated by Django 3.2.13 on 2022-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacarnaval',
            name='dia',
            field=models.CharField(default='', max_length=8),
        ),
    ]
