# Generated by Django 3.2.13 on 2022-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendacarnaval_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesdositedecarnaval',
            name='primeiro_dia_de_carnaval',
            field=models.DateField(default='2022-05-15'),
        ),
    ]
