# Generated by Django 3.2.13 on 2022-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220503_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgramiacaoCarnaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=54)),
                ('escola', models.CharField(max_length=54)),
                ('texto', models.TextField()),
            ],
        ),
    ]
