# Generated by Django 3.2.13 on 2022-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agramiacaocarnaval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgramiacaoCarnaval',
            new_name='AgremiacaoCarnaval',
        ),
    ]
