# Generated by Django 3.2.13 on 2022-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_agramiacaocarnaval_agremiacaocarnaval'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosCarnaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=54)),
                ('legenda', models.CharField(max_length=54)),
            ],
        ),
    ]
