# Generated by Django 3.2.13 on 2022-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventoscarnaval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcursosCarnaval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=54)),
            ],
        ),
    ]
