# Generated by Django 3.2.12 on 2023-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_concursoscarnaval'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesdositedecarnaval',
            name='texto03',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='informacoesdositedecarnaval',
            name='texto04',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='informacoesdositedecarnaval',
            name='texto05',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='informacoesdositedecarnaval',
            name='titulo03',
            field=models.CharField(default='', max_length=45),
        ),
    ]
