# Generated by Django 3.2.12 on 2023-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230116_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesdositedecarnaval',
            name='texto03',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informacoesdositedecarnaval',
            name='texto04',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informacoesdositedecarnaval',
            name='texto05',
            field=models.TextField(blank=True, default=''),
        ),
    ]
