# Generated by Django 3.2.12 on 2023-01-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230116_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_evento', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_eventos', verbose_name='img')),
                ('legenda', models.CharField(max_length=54)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='EventosCarnaval',
        ),
        migrations.AddField(
            model_name='agendacarnaval',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='agendacarnaval',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='agendacarnaval',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='agremiacaocarnaval',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_agremiacao', verbose_name='img'),
        ),
    ]
