# Generated by Django 3.2.12 on 2023-01-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230116_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_do_Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=54)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_concurso', verbose_name='img')),
            ],
        ),
        migrations.AddField(
            model_name='concursoscarnaval',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Fotos_Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_concurso', verbose_name='img')),
                ('legenda', models.CharField(max_length=54)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
        ),
    ]
