# Generated by Django 3.2.13 on 2022-09-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0002_auto_20220927_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
