# Generated by Django 3.2.13 on 2022-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0003_rename_eventos_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Nome da pessoa')),
                ('foto', models.ImageField(upload_to='testemonios_fotos', verbose_name='Imagem/foto para divulgação do evento')),
                ('comentario', models.DateField()),
            ],
        ),
    ]
