# Generated by Django 3.2.13 on 2022-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0004_testemonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemonio',
            name='comentario',
            field=models.CharField(max_length=150),
        ),
    ]
