# Generated by Django 3.2.13 on 2022-10-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0006_auto_20220927_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testemonio',
            new_name='Testemunho',
        ),
    ]
