# Generated by Django 3.2.16 on 2022-11-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0007_rename_testemonio_testemunho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=256, verbose_name='Endereço do local')),
                ('link', models.URLField(null=True, verbose_name='Link do google maps para o local')),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do evento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='natal.local')),
            ],
            options={
                'verbose_name': 'Programação',
                'verbose_name_plural': 'Programação',
            },
        ),
    ]
