# Generated by Django 3.2.16 on 2022-11-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0009_auto_20221122_1445'),
        ('natal', '0009_auto_20221124_2007'),
    ]

    operations = [
    ]
